### ISSUE TITLE
쿠버네티스 리소스 개념 이해하기

### ISSUE THREAD

**Issue by iiogmgo** [yangroro/cloud-studyjam-entry#3]
Pod, Node, Deployment, Service 등 다양한 개념이 등장하는데요.
제가 이해한 게 맞는지 여러분의 도움이 필요합니다 :)
손으로 그린 초안이 잘못 되어서 덮어씌웠어요..

1. pod : K8s의 가장 작은 배포 단위
- 컨테이너의 집합
- 컨테이너 간 리소스 공유 가능

2. node : 물리서버
- pod 는 늘 node 위에 있음

3. deployment 
- 애플리케이션 인스턴스들의 생성과 업데이트를 책임

4. service
- pods에 포함된 컨테이너의 트래픽 로드 밸런싱을 지원

![kuber_archi](https://user-images.githubusercontent.com/9989554/50971498-7b6a9080-1527-11e9-8398-4e5e2d9cda12.png)

**Comment by yangroro** [comment]
Master는 고가용성 보장이 되나요?
: 고가용성 보장이 됩니다.
https://thenewstack.io/kubernetes-high-availability-no-single-point-of-failure/

**Comment by chjinlook** [comment]
포드는 하나 이상의 컨테이너가 포함된 집합을 의미합니다. 일반적으로 종속도가 높은 여러 컨테이너가 있을 경우 컨테이너들을 단일 포드로 패키징합니다.

**Comment by chjinlook** [comment]
![image](https://user-images.githubusercontent.com/45680035/51025425-56c9f380-15cf-11e9-9761-541c76d8a1b0.png)

**Comment by chjinlook** [comment]
서비스는 포드를 위한 안정적인 엔드포인트를 제공합니다.

**Comment by chjinlook** [comment]
![image](https://user-images.githubusercontent.com/45680035/51026269-77934880-15d1-11e9-85b3-66d57f9187fa.png)
