### ISSUE TITLE
Headless service

### ISSUE THREAD

**Issue by brightparagon** [yangroro/cloud-studyjam-entry#6]
Headless service 설명을 보아도 왜 만들어야 하는지, 어떤 점에서 필요한지 등에 대해 잘 와닿지 않습니다.
아래 링크를 보면 개별적인 pod에 접근할 수 있다 정도인 것 같은데 어떤 맥락에서 이렇게 사용할 수 있을지 모르겠네요.

https://www.quora.com/What-is-the-use-of-a-headless-service-in-Kubernetes

**Comment by iiogmgo** [comment]
http://bcho.tistory.com/1262

음, 저는 이 글보고 이해가 좀 되었는데 도움이 되면 좋겠네요-

**Comment by yangroro** [comment]
https://stackoverflow.com/questions/46456239/how-to-expose-a-headless-service-for-a-statefulset-externally-in-kubernetes

**Comment by brightparagon** [comment]
https://stackoverflow.com/questions/51196903/do-we-really-need-port-for-a-headless-service

kubectl이 제공해주는 functionality로 해결할 수 없는 문제들이 있을 수 있다.
- Database 인스턴스들 중에 특정 인스턴스에 접근해서 마이그레이션 하거나, 다른 service로 옮겨야 하는 경우
- Cluster를 잘못 만들어서 새 Cluster로 기존 service 안에 있는 pod들을 옮겨야 하는 경우
- 이외에 쪼렙으로서 상상할 수 없는 온갖 복잡한 infra-low-level 로 무언가 관리해야하는 경우들

이런 경우에는 독립적인 instance에 접근할 필요성이 생기는데 Headless Service가 도움이 될 수 있다.
